# Generated by Django 5.2.1 on 2026-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('text', 'Văn bản'), ('file', 'Tệp'), ('url', 'URL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluator_type',
            field=models.CharField(choices=[('ai', 'AI'), ('human', 'Người')], default='human', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('user', 'Người dùng')], default='user', max_length=20),
        ),
    ]
