# Generated by Django 5.2.16 on 2026-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_alter_document_source_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetting',
            options={'verbose_name': 'Cài đặt', 'verbose_name_plural': 'Cài đặt'},
        ),
        migrations.AddField(
            model_name='usersetting',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='API key Gemini cá nhân (nếu có)', max_length=255),
        ),
    ]
