# Generated by Django 5.2.16 on 2026-07-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_alter_usersetting_options_usersetting_gemini_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarysentence',
            name='is_highlighted',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
