# Generated by Django 5.2.16 on 2026-07-29 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_remove_summarysentence_is_highlighted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at'], 'select_on_save': False},
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-created_at'], name='summaries_d_user_id_4e4326_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['user', '-created_at'], name='summaries_s_user_id_3d9dd0_idx'),
        ),
    ]
