# Generated by Django 5.2.16 on 2026-07-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0006_add_db_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
