# Generated by Django 5.2.16 on 2026-09-01 18:55

from django.db import migrations, models
from django.utils.text import slugify


def backfill_tag_slugs(apps, schema_editor):
    Tag = apps.get_model("summaries", "Tag")
    used = set()
    for tag in Tag.objects.all().order_by("id"):
        base = slugify(tag.name, allow_unicode=True) or f"tag-{tag.id}"
        slug = base
        n = 2
        while slug in used:
            slug = f"{base}-{n}"
            n += 1
        used.add(slug)
        tag.slug = slug
        tag.save(update_fields=["slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0007_alter_document_options_alter_summary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_tag_slugs, noop),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='language',
            field=models.CharField(default='auto', max_length=20),
        ),
    ]
