# Generated by Django 5.2.16 on 2026-09-08 16:34

import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0008_add_tag_slug_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['search_vector'], name='summaries_s_search__c92837_idx'),
        ),
    ]
