# Generated by Django 5.2.16 on 2026-09-16 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0011_webhookregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang gửi'), ('delivered', 'Đã gửi'), ('failed', 'Gửi thất bại')], default='pending', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='summaries.summary')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='summaries.webhookregistration')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='summaries_w_status_aa10dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('webhook', 'summary', 'event'), name='unique_webhook_summary_event')],
            },
        ),
    ]
