# Generated by Django 5.2.16 on 2026-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0012_durable_webhook_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookregistration',
            name='events',
            field=models.JSONField(default=list, help_text="List of events to subscribe to: ['summary.completed']"),
        ),
    ]
