# Generated by Django 5.2.16 on 2026-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0013_summary_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('user', 'Người dùng')], default='user', help_text='Metadata cũ; quyền truy cập dùng is_staff/is_superuser của Django.', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='language_preference',
            field=models.CharField(default='auto', help_text='Chưa áp dụng; ngôn ngữ hiện được nhận diện từ nội dung.', max_length=20),
        ),
    ]
