### Home
GET http://localhost:8000/

### Login page
GET http://localhost:8000/login/

### Create summary with text
POST http://localhost:8000/api/summaries/create/
Content-Type: application/x-www-form-urlencoded

source_type=text&method=textrank&text=Day%20la%20mot%20doan%20van%20ban%20de%20kiem%20thu%20he%20thong%20tom%20tat%20Django.&ratio=0.4
