name: Auto-assign PR

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign
        uses: posva/auto-assign-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          assignees: "NgHuuGiau"
          num-of-assignees: 2
          skip-keywords: "wip,draft,do not merge,do-not-merge"
          allow-self-assignment: false
          add-reviewers: true
          reviewer-keywords: "wip,draft,do not merge,do-not-merge"
